services:
  postgres:
    image: postgres:16-alpine
    container_name: job_market_postgres_py
    environment:
      POSTGRES_DB: job_market-py
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_py:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d job_market-py"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  postgres_data_py:
    name: postgres_data_py
